### ISSUE TITLE
Need help !!!

### ISSUE THREAD

**Issue by NguyenASang** [FriedChickenButt/youtube-webos#14]
Can anyone help me this error ? I stuck at this step :(
![image](https://user-images.githubusercontent.com/87893636/126886921-8eff5c10-75f7-4570-8b22-69d02bd97a71.png)

**Comment by FriedChickenButt** [comment]
Can you please try replacing `{npm_package_version}` with  0.0.2?

**Comment by NguyenASang** [comment]
> Can you please try replacing `{npm_package_version}` with 0.0.2?

In package.json, package-lock.json right ?

**Comment by FriedChickenButt** [comment]
Sorry for the late reply. 

You have to install dependencies, build and then deploy:

Run the commands in the given sequence.

Install dependencies:
```sh
npm install
```

Build:
```sh
npm run build && npm run package
```

Install:
```sh
npm run deploy
```

**Comment by NguyenASang** [comment]
"npm run deloy" Is this a command to install youtube to emulator or TV

**Comment by FriedChickenButt** [comment]
yes, that's the command to install on TV. However, I didn't try running on Emulator. It ran too slow on any system.

You have a typo in your command, correct one is:
```
npm run deploy
```

**Comment by NguyenASang** [comment]
Ye Thanks for your help. I can do that only on emulator but can't on my TV cuz it can't download develop mode 🙂and I don't know why 😢
