### ISSUE TITLE
Change app icon

### ISSUE THREAD

**Issue by NguyenASang** [FriedChickenButt/youtube-webos#17]
Can you pls change the icon to this :D
![image](https://user-images.githubusercontent.com/87893636/130733534-d977e4e6-bbaf-4b5d-86ce-dc48312cb5e6.png)

Can I change it by change the picture and edit appinfo.json ?

**Comment by itsRealM12C** [comment]
Yes, you can change it by replacing icon.png ang largeIcon.png to the youtube logo one.
