### ISSUE TITLE
Remove Youtube login popup

### ISSUE THREAD

**Issue by NguyenASang** [FriedChickenButt/youtube-webos#22]
I know cuz some reason so this "Youtube" can't be sign in so we need to remove this pop up ( it appears every time I watch a video )

![241759869_925964231324724_7119786084192135135_n](https://user-images.githubusercontent.com/87893636/133374161-0b0beab8-8f34-4755-bd49-c1320f964e1e.jpg)
 
Translate:
`Đăng nhập để có trải nghiệm tuyệt vời nhất trên Youtube`
Sign in for the best YouTube experience

`Bạn chưa có tài khoản? Hãy tạo tài khoản miễn phí tại youtube.com/signup`
Don't have an account? Create a free account at youtube.com/signup

`Đăng nhập`
Login

`Để sau`
Later

**Comment by recon08** [comment]
I could sign in without any issue :thinking:

**Comment by NguyenASang** [comment]
> I could sign in without any issue 🤔

Really 😯 I tried but I can't. Do you need to restart "Youtube dev" app ?

**Comment by NguyenASang** [comment]
Oh I'm wrong 😅
