### ISSUE TITLE
Watch history not being saved

### ISSUE THREAD

**Issue by Stari89** [FriedChickenButt/youtube-webos#24]
Watch history does not seem to save.
https://youtu.be/BbOqAhKU4rg
As you can see in the video, when I start watching a random video in the TV app, video is not saved to watch history. Then I start watching a video on my laptop (signed in with the same account) and the video is correctly shown in the watch history on the TV.

**Comment by NguyenASang** [comment]
Can you try to log out then log in to your account ? 
If it doesn't work, maybe this is a bug

**Comment by Stari89** [comment]
OK I investigated this a little bit more.
When I'm logged in to YouTube, I can select my personal account (Damjan Kovačič), or I can select one of my brand accounts. 100% of the time I'm using my brand account (Damjan's Workshop).
When I switched to my personal account, the watch history was saved just fine. Then I switched back to my brand account and the watch history saving stopped working again.
I tried completely resetting the app, no success, the history wasn't saved in the brand account.
Cheers!
![1631890508299](https://user-images.githubusercontent.com/34682711/133805273-e8dc53bc-f49c-44f3-955b-a72018edcc8d.jpg)

**Comment by Stari89** [comment]
More info: I installed a Smart TV Emulator Chrome Extension. I navigated to https://www.youtube.com/tv and logged with my personal account. The watch history was being saved. Then I logged in with my brand account, and sure enough, the history was not saved anymore.
I'm not sure if this is a YT HTML5 client bug or there may be a special case when being logged in with a brand account requires some special handling in the wrapper app.
Cheers

**Comment by Stari89** [comment]
Lol why didn't I think of this sooner?
I tried the same thing in the official YouTube app. I got the same result, but I got an ad before the video! :) I'm closing this ticket, because the bug is clearly not on youtube-webos's side.
Cheers!

**Comment by Informatic** [comment]
FYI fix for this has been rolled out in webosbrew/youtube-webos v0.2.0 - https://github.com/webosbrew/youtube-webos/releases/tag/v0.2.0
