### ISSUE TITLE
ares-install ERR! Error: connect ECONNREFUSED 127.0.0.1:6622

### ISSUE THREAD

**Issue by Cr4z33** [FriedChickenButt/youtube-webos#38]
Although everything looks being setup properly I get this error when trying to send the IPK to my C1 "48.

Here is the full error:
`cr4z33@CR4Z33-STUDIO:~/youtube-webos$ npm run deploy

> youtube-webos@0.0.2 deploy
> ares-install youtube.leanback.v4_${npm_package_version}_all.ipk

ares-install ERR! Error: connect ECONNREFUSED 127.0.0.1:6622`

and here are some infos from the installed webOS SDK:
`cr4z33@CR4Z33-STUDIO:~/youtube-webos$ ares-setup-device --list
name           deviceinfo                connection  profile
-------------  ------------------------  ----------  -------
tv2 (default)  root@192.168.1.232:9922   ssh         tv
emulator       developer@127.0.0.1:6622  ssh         tv`
`cr4z33@CR4Z33-STUDIO:~/youtube-webos$ ares-device-info --device tv2
modelName : OLED48C15LA
sdkVersion : 6.3.1
firmwareVersion : 03.33.11
boardType : O20N_DVB_EU
otaId : HE_DTV_W21O_AFABATAA`

Please help. 😭

**Comment by Cr4z33** [comment]
Code formatting is looking weird here... so I've put everything in a Pastebin:
https://pastebin.com/ZU43ZQnU

**Comment by emise** [comment]
See this https://github.com/FriedChickenButt/youtube-webos/issues/13

**Comment by Cr4z33** [comment]
> See this #13
> 
> Also it looks like this repo is no longer maintained; I've been getting updates from here https://github.com/webosbrew/youtube-webos

Oh correct I got also the SSH key following the tut on the dev webOS website!

Thanks for the new link.
