### ISSUE TITLE
Are you based on Invidious?

### ISSUE THREAD

**Issue by PiRomant** [FriedChickenButt/youtube-webos#5]
Are you based on https://github.com/iv-org/invidious ?

**Comment by Informatic** [comment]
No, this is essentially a remake of official YouTube TV app (which is just a web browser opened at `https://youtube.com/tv`)

**Comment by PiRomant** [comment]
Do you plan to use instances https://redirect.invidious.io/, for example, to increase the playback speed?

**Comment by Informatic** [comment]
From what I can tell invidious is just an alternative frontend to youtube - do you mean any specific features you want implemented in YouTube TV app from there?

**Comment by PiRomant** [comment]
Lightweight
No ads
No tracking
Set default player options (speed, quality, autoplay, loop)

Attach the arrow control to the interface.
As main page use any from https://redirect.invidious.io/
For DiAL use https://github.com/iv-org/invidious/issues/1321

**Comment by Informatic** [comment]
Making an "app" from a webpage is a rather simple task. (you can just replace the URL here: https://github.com/FriedChickenButt/youtube-webos/blob/main/index.js#L2) The bigger issue is actually adapting invidious to be *actually* usable in a TV setting. Feel free to take it up, but this is definitely not a priority here. (and I guess would more fit as a task for Invidious, to make a TV-style UI - then we would gladly help packaging it up as a webOS webapp, but likely a completely separate one from this project)
